/// @file mouth_script.hpp
/// @brief Jaw keyframes synced to voice.mp3.
///
/// GENERATED by tools/make_jaw_script.py -- do not edit by hand. Re-run the
/// script whenever the voice clip changes.

#pragma once

#include <stdint.h>

namespace skeleton
{

/// @brief One step of the jaw script.
struct Keyframe
{
  uint8_t open_pct;   ///< 0 = closed, 100 = fully open.
  uint16_t hold_ms;   ///< How long to stay here before the next frame.
};

/// Jaw openness over time, starting when the voice starts playing. The
/// hold times add up to the clip length (3297 ms).
constexpr Keyframe SPEECH[] = {
    {0U, 240U},
    {25U, 60U},
    {50U, 60U},
    {100U, 180U},
    {75U, 60U},
    {50U, 60U},
    {100U, 60U},
    {25U, 60U},
    {0U, 720U},
    {75U, 60U},
    {100U, 60U},
    {50U, 60U},
    {75U, 240U},
    {25U, 60U},
    {0U, 60U},
    {25U, 60U},
    {50U, 120U},
    {25U, 120U},
    {0U, 60U},
    {50U, 120U},
    {100U, 240U},
    {75U, 60U},
    {25U, 60U},
    {0U, 417U},
};

}  // namespace skeleton
