"""Generate mouth_script.hpp (jaw keyframes) from sd_card/voice.mp3.

The jaw opening follows the loudness of the voice, sampled in fixed frames
and quantized to a few levels so the servo gets clean, distinct moves.

Requires: python3 with numpy, and ffmpeg on the PATH.
Usage:    python3 tools/make_jaw_script.py [path/to/voice.mp3]
"""

import subprocess
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MP3 = ROOT / "sd_card" / "voice.mp3"
HEADER = ROOT / "mouth_script.hpp"

SAMPLE_RATE = 16000
# A hobby servo needs ~60-80 ms to swing the jaw; faster frames just blur.
FRAME_MS = 60
# Voice band used to measure loudness; drops rumble and hiss/echo tails.
BAND_LOW_HZ = 300
BAND_HIGH_HZ = 3000
# Syllables are peaks above the slow loudness trend; subtracting part of
# that trend makes the jaw close between syllables in continuous speech.
FAST_WINDOW_MS = 30
SLOW_WINDOW_MS = 300
TREND_WEIGHT = 0.35
# Articulation (0..1 of peak) at which the jaw starts to open / is fully
# open.
OPEN_START = 0.06
OPEN_FULL = 0.60
# Openness levels in percent; quantizing avoids constant servo jitter.
LEVEL_STEP_PCT = 25


def load_mono(path):
    raw = subprocess.run(
        ["ffmpeg", "-v", "error", "-i", str(path), "-f", "f32le", "-ac", "1",
         "-ar", str(SAMPLE_RATE), "-"],
        capture_output=True, check=True).stdout
    return np.frombuffer(raw, dtype=np.float32)


def band_limit(samples):
    """Keep only the voice band using an FFT mask."""
    spectrum = np.fft.rfft(samples)
    freqs = np.fft.rfftfreq(len(samples), 1.0 / SAMPLE_RATE)
    spectrum[(freqs < BAND_LOW_HZ) | (freqs > BAND_HIGH_HZ)] = 0.0
    return np.fft.irfft(spectrum, len(samples))


def moving_rms(samples, window_ms):
    width = max(SAMPLE_RATE * window_ms // 1000, 1)
    power = np.convolve(samples ** 2, np.ones(width) / width, "same")
    return np.sqrt(power)


def frame_openness(samples):
    """Openness percent for each FRAME_MS frame."""
    voice = band_limit(samples)
    fast = moving_rms(voice, FAST_WINDOW_MS)
    slow = moving_rms(voice, SLOW_WINDOW_MS)
    articulation = np.clip(fast - TREND_WEIGHT * slow, 0.0, None)
    articulation /= max(float(articulation.max()), 1e-9)

    frame_len = SAMPLE_RATE * FRAME_MS // 1000
    count = len(articulation) // frame_len
    level = articulation[:count * frame_len].reshape(count, frame_len)
    level = level.mean(axis=1)
    ratio = np.clip((level - OPEN_START) / (OPEN_FULL - OPEN_START), 0.0, 1.0)
    return (np.round(ratio * 100 / LEVEL_STEP_PCT) * LEVEL_STEP_PCT).astype(int)


def merge(openness, total_ms):
    """Collapse runs of equal openness into (open_pct, hold_ms) keyframes."""
    keyframes = []
    for pct in openness:
        if keyframes and keyframes[-1][0] == pct:
            keyframes[-1][1] += FRAME_MS
        else:
            keyframes.append([int(pct), FRAME_MS])
    # Make the script last exactly as long as the clip, ending shut.
    covered = len(openness) * FRAME_MS
    if keyframes[-1][0] != 0:
        keyframes.append([0, 0])
    keyframes[-1][1] += max(total_ms - covered, 0)
    return keyframes


def write_header(keyframes, total_ms, source):
    rows = "\n".join(f"    {{{pct}U, {ms}U}}," for pct, ms in keyframes)
    HEADER.write_text(f"""/// @file mouth_script.hpp
/// @brief Jaw keyframes synced to {source.name}.
///
/// GENERATED by tools/make_jaw_script.py -- do not edit by hand. Re-run the
/// script whenever the voice clip changes.

#pragma once

#include <stdint.h>

namespace skeleton
{{

/// @brief One step of the jaw script.
struct Keyframe
{{
  uint8_t open_pct;   ///< 0 = closed, 100 = fully open.
  uint16_t hold_ms;   ///< How long to stay here before the next frame.
}};

/// Jaw openness over time, starting when the voice starts playing. The
/// hold times add up to the clip length ({total_ms} ms).
constexpr Keyframe SPEECH[] = {{
{rows}
}};

}}  // namespace skeleton
""")


def main():
    mp3 = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_MP3
    samples = load_mono(mp3)
    total_ms = len(samples) * 1000 // SAMPLE_RATE
    keyframes = merge(frame_openness(samples), total_ms)
    write_header(keyframes, total_ms, mp3)
    print(f"{len(keyframes)} keyframes, {total_ms} ms -> {HEADER}")


if __name__ == "__main__":
    main()
